{
    "name": "RandomIpDevice",
    "version": "1.1.9",
    "icon": "fas fa-network-wired",
    "category": "household",
    "author": "philipp2310",
    "maintainers": [],
    "desc": "Monitor and access any device reachable via ip",
    "aliceMinVersion": "1.0.0-rc1",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        "icmplib"
    ],
    "conditions": {
        "lang": [
            "en",
            "de"
        ],
        "asrArbitraryCapture": false
    }
}
