{
    "name": "RandomIpDevice",
    "version": "1.0.0",
    "icon": "fas fa-network-wired",
    "category": "household",
    "author": "philipp2310",
    "maintainers": [],
    "desc": "Monitor any device reachable via ip",
    "aliceMinVersion": "1.0.0-b1",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
    ],
    "conditions": {
        "lang": [
            "en",
            "de"
        ],
        "asrArbitraryCapture": false
    }
}
